baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Nic's Data Science Portfolio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Resume
      url: '#resume'
      weight: 5
 #   - name: Blog
 #     url: blog
 #     weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
#    - name: Blog
#      url: blog
#      weight: 2
params:
 # blogPageURL: blog
  contactButtonLabel: Contact Nic
  contactLink: '#contact'
  copyright: All right reserved copyright ©
  footerLogo: images/site-navigation/logonic.png
  formspreeURL: https://formspree.io/f/mvonbeok
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logonic.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/nic-rocha/
      weight: 1
   
